### ISSUE TITLE
Centralized Workflows repository as source for all workflows

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [frmscoe/workflows#12]
To streamline our workflow management, a new workflow named **sync-workflows** to be created. This workflow aims to automate the process of updating workflows across all repositories by leveraging the centralized workflows repository. The sync-workflows job runs in the central workflow repository and, upon merging a pull request into the `dev` branch, it creates pull requests to update the workflows in all relevant repositories.

### Workflow Details:
- **sync-workflows**:
  - This workflow triggers when a pull request is closed and merged into the `dev` branch of the central workflow repository.
  - It automatically generates pull requests in all repositories, including the additional workflows added to the central repository.
  - This process eliminates the need to manually create pull requests in each repository, ensuring consistency and saving time.

### Tasks:
- Implement the **sync-workflows** in the centralized workflow repository.
- Ensure the workflow runs smoothly and creates pull requests in all target repositories when changes are merged into `dev`.
- Test the workflow thoroughly to confirm it updates all repositories correctly.
- Update the documentation in the centralized workflow repository to include details about the sync-workflows job and how it functions.

**Comment by vorsterk** [comment]
Tested and approved with scott , turned off for now till we relook at additional docker workflows etc..

Its in the `workflows` repo .
