### ISSUE TITLE
Create new workflows

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [frmscoe/workflows#14]
We need to enhance our centralized workflow repository by adding three new workflows. These workflows are essential for maintaining high standards in our codebase and ensuring compliance with our contribution guidelines. The workflows to be added are as follows:

1. **Conventional Commits**:
   - This workflow ensures that all commit messages adhere to the Conventional Commits specification. It helps in creating an explicit commit history, which makes it easier to write automated tools on top of.
   - Reference: [Conventional Commits Specification](https://www.conventionalcommits.org/en/v1.0.0/)

2. **DCO-Check**:
   - The Developer Certificate of Origin (DCO) workflow checks that each commit contains a "Signed-off-by" line with the contributor's name and email address, signifying agreement to the DCO.
   - Reference: [Developer Certificate of Origin](https://developercertificate.org/)

3. **Gpg-Verify**:
   - This workflow verifies the GPG signatures of commits to ensure the authenticity and integrity of the contributions. Only commits signed with a recognized GPG key will be accepted.
   - Reference: [GPG Verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification)

### Tasks:
- Implement the **Conventional Commits** workflow.
- Implement the **DCO-Check** workflow.
- Implement the **Gpg-Verify** workflow.
- Test each workflow to ensure they function correctly.
- Update the documentation in the centralized workflow repository to include details about the new workflows and how they are used.

**Comment by vorsterk** [comment]
Task complete and implemented into all necessary repos
